### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by guillaumealgis** [disqus/django-bitfield#119]
Hi, do you have any plans for a new release of this package on pypi ?
There's been a few useful commits in the last year that we'd be happy to have in an official release instead of having to fetch code from a git branch :)

Thank you!

**Comment by mromagnoli** [comment]
Seconding this request 🤚

**Comment by timabbott** [comment]
Yes, working on this now.

**Comment by timabbott** [comment]
OK, released 3.2.0.  Sorry for the delay -- my time for side projects like maintaining this has been very low due to a new baby :).

**Comment by timabbott** [comment]
Haha, yes, wasn't looking at my keyboard and I guess my hand was a key over from where I thought it was :)
