### ISSUE TITLE
.filter(flags=Model.flags.flag1 & Model.flags.flag2) not working

### ISSUE THREAD

**Issue by MikeVL** [disqus/django-bitfield#22]
Model.flags.flag1 & Model.flags.flag2 is always equal zero

I can`t filter by two or more flags

**Comment by moggers87** [comment]
`&` is a bitwise `AND`, so this will always return 0 when combining flags. I think you meant to use `Model.flags.flag1 | Model.flags.flag2`

This issue can be closed.

**Comment by MikeVL** [comment]
Thanks.
