### ISSUE TITLE
Python 2.5 does not support the tuple.index() method

### ISSUE THREAD

**Issue by michaelgodshall** [disqus/django-bitfield#4]
The BitField does not seem to support Python 2.5 because the tuple.index() method was not introduced until 2.6.  If this is intended, it would be good to add a Python 2.6 requirement to the readme.  Otherwise, here's the error message that pops up whenever __ getattr __, __ setattr __, and __ contains __ are used for BitHandler:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/.../bitfield/**init**.py", line 217, in iteritems
    yield (k, getattr(self, k).is_set)
  File "/.../bitfield/**init**.py", line 178, in **getattr**
    return self.get_bit(self._keys.index(key))
AttributeError: 'tuple' object has no attribute 'index'

I was able to solve this by turning "self._keys.index(key)" to "list(self._keys).index(key)", but I'm not sure if this is the best approach.  I just wanted you to be aware of the tuple.index() issue in case you wanted to support Python 2.5.

**Comment by BYK** [comment]
We don't support Python 2.5 and don't have any good reason to support it from now on at this point so closing.
