### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by jgastal** [disqus/django-bitfield#40]
The latest release, 1.6.4, is quite old, a new release would be very welcome.

**Comment by IronLemon** [comment]
One more vote for a new release, especially for https://github.com/disqus/django-bitfield/pull/51

**Comment by hiisi13** [comment]
@IronLemon +1!

**Comment by christianhesslemonade** [comment]
This project is really abandoned. Not working in 1.7.5

**Comment by timdawborn** [comment]
+1

**Comment by dcramer** [comment]
As soon as MySQL support is fixed in master we'll create a new release.

That said, I don't use MySQL nor do I get paid to fix this, so its unlikely it'll happen without a PR.

**Comment by dcramer** [comment]
Refs #59

**Comment by hellpain** [comment]
@IronLemon +1!

**Comment by dcramer** [comment]
I've released 1.8.0

**Comment by chessbr** [comment]
A lot of thanks!!!
