### ISSUE TITLE
Can`t run tests on python 3.4 and django 1.7rc1

### ISSUE THREAD

**Issue by hellpain** [disqus/django-bitfield#45]
Hello!
I have the following env:
Python 3.4.1
Django==1.7c1
django-bitfield==1.7.0
django-nose==1.2
nose==1.3.3
psycopg2==2.5.3
six==1.7.3

When I try to run 'python runtests.py' I get an error:
....
....
  File "/home/hellpain/.virtualenvs/nedviga/lib/python3.4/site-packages/django/apps/registry.py", line 119, in check_ready
    raise AppRegistryNotReady()
django.core.exceptions.AppRegistryNotReady

In django 1.7 app loading module was refactored, so django-bitfield makes smth wrong.

I had to run tests because in my env I can`t save model with bit-fields in django admin, I wanted to find an error, but even couldn`t run tests=))

Thank you for your attention.

**Comment by dcramer** [comment]
Closing as fixed.
