### ISSUE TITLE
BitField broken on upcoming Django 1.8

### ISSUE THREAD

**Issue by LukeSkyw** [disqus/django-bitfield#57]
Hi,
Following this commit on Django master (upcoming stable 1.8):

    commit f59fd15c4928caf3dfcbd50f6ab47be409a43b01
    Author: Josh Smeaton <josh.smeaton@gmail.com>
    Date:   Thu Dec 26 00:13:18 2013 +1100

    Fixed #14030 -- Allowed annotations to accept all expressions

django.db.models.sql.expressions module has been removed, with the SQLEvaluator along with it. This SQLEvaluator is used by BitField:

    [...]
        from bitfield import BitField
      File "/home/luke/development/django-1.8c1-env/local/lib/python2.7/site-packages/bitfield/__init__.py", line 12, in <module>
        from bitfield.models import Bit, BitHandler, CompositeBitField, BitField  # noqa
      File "/home/luke/development/django-1.8c1-env/local/lib/python2.7/site-packages/bitfield/models.py", line 2, in <module>
        from django.db.models.sql.expressions import SQLEvaluator
    ImportError: No module named expressions

I have no idea of the amount of work necessary to get rid of SQLEvaluator. Can bitfield maintainer fix this?

**Comment by iorlas** [comment]
Hey, we really need it!

**Comment by paulochf** [comment]
+1, I got the same problem here.

**Comment by Sharpek** [comment]
+1

**Comment by lehins** [comment]
+1
