### ISSUE TITLE
Support Django 1.10

### ISSUE THREAD

**Issue by tzachyrm** [disqus/django-bitfield#67]
In Django 1.8, SubfieldBase has been deprecated and will be removed in Django 1.10.
I'm using Django 1.9 and getting "RemovedInDjango110Warning".

**Comment by fluffels** [comment]
+1

**Comment by atugushev** [comment]
I'm just wondering, is this package alive?

**Comment by mattbasta** [comment]
@dcramer Are you still owning this package? Is there someone at Disqus that can be contacted about this, or would it be wiser to migrate to another package?

**Comment by dcramer** [comment]
I can't speak to any other maintainers but we don't use django 1.10 and I don't have time to maintain thing a we're not using.

**Comment by atugushev** [comment]
I'd like to propose to move this project to [JazzBand](https://github.com/jazzband/) with agreement of the author. I hope our community will help to keep this package up to date. @dcramer don't you know who is the author/owner?

**Comment by strycore** [comment]
I have a fork here:  https://github.com/lutris/django-bitfield where I merged @znotdead 's PR ( https://github.com/disqus/django-bitfield/pull/71 ) and did some additional work to update the project. My goal is to have the tests pass on all supported Django versions but I currently have failures with simple_class_factory being removed in 1.10 and some pickle voodoo in the test suite. (Test suite results here: https://travis-ci.org/lutris/django-bitfield )

There's also a Python 3 error with 1.9 but I haven't looked at it yet. 
Once the project is stable it will be easier to get it merged back in the main repo, I'll accept any pull request for this.

**Comment by strycore** [comment]
And now all test pass thanks to @joshowen's patches: https://travis-ci.org/lutris/django-bitfield

@dcramer, you should seriously consider giving push access to this repository to someone willing to maintain the project or at least give access to the PyPI page so someone can switch the location to a maintained branch.

**Comment by OOPMan** [comment]
@strycore If this project seems to be unmaintained then I would recommend you fork it with a new name and release.

**Comment by jsferrei** [comment]
@tail I notice you're part of the Disqus org -- any thoughts on this project?

**Comment by joshowen** [comment]
All tests are passing on https://github.com/disqus/django-bitfield/pull/74

**Comment by joshowen** [comment]
This is merged to master, waiting on a release to pypi.

**Comment by joshblum** [comment]
@joshowen thanks for fixing!! do you know when the pypi release will happen?

**Comment by joshowen** [comment]
@christian-oudard any ETA on a pypi release?

**Comment by s0nskar** [comment]
any update on release ??

**Comment by pacahon** [comment]
Any news about pypi release? :)

**Comment by BYK** [comment]
19.2 is out with support for Django 1.4 to 1.10 and Python 2.7, Python 3.4 and Python 3.5
