### ISSUE TITLE
pip release ?

### ISSUE THREAD

**Issue by DylannCordel** [disqus/django-bitfield#76]
Last version on pip is still 1.8.0.
Could you release newer versions on pip please ?

**Comment by joshblum** [comment]
@christian-oudard any update?

**Comment by joshblum** [comment]
@BYK would it be possible to release on pypi?

**Comment by BYK** [comment]
19.2 is out with support for Django 1.4 to 1.10 and Python 2.7, Python 3.4 and Python 3.5

**Comment by DylannCordel** [comment]
Thx @BYK !

**Comment by joshblum** [comment]
Thanks @BYK !!
