### ISSUE TITLE
runserver fails with Django 3.0 due to postgres_psycopg2 reference in types.py

### ISSUE THREAD

**Issue by rystan** [disqus/django-bitfield#96]
As per https://docs.djangoproject.com/en/2.0/releases/2.0/#id1:

> The django.db.backends.postgresql_psycopg2 module is deprecated in favor of django.db.backends.postgresql. It’s been an alias since Django 1.9. This only affects code that imports from the module directly. The DATABASES setting can still use 'django.db.backends.postgresql_psycopg2', though you can simplify that by using the 'django.db.backends.postgresql' name added in Django 1.9.

The alias must have been removed in Django 3.0 release.

Removing the '_psycopg2' from the call in types.py lets a project build again.

**Comment by timabbott** [comment]
Can you submit a PR?

-Tim Abbott (mobile)

**Comment by rystan** [comment]
Hi @timabbott ,  I did already.  :)  PR #97
