### ISSUE TITLE
Release of django-bitfield compliant with django2.2

### ISSUE THREAD

**Issue by moumoutte** [disqus/django-bitfield#99]
Hi There!

Since django2.2 will become soon the new LTS version, I'm wondering if you can provide a new release of django-bitfield compliant with this version. I've seen in commit history since the 3rd september the compliance is guarantee for django >=1.10 (893b5ae232de88c8368a41b40865459a9e1d11e5), can you please release a new version with those commits ?

I've seen on pypi the last available release has been done the 13th July 2019.

Many thxs!

**Comment by timabbott** [comment]
Have you tested an install of this package from Git against Django 2.2?  

I have time to post a pypi release sometime in the next few days.

**Comment by bernd-wechner** [comment]
Django 3.0 is out, and I migrated my dev box to that and Python 3.8 recently and I don't recall running into any bitfield issues. What does compliance mean in this instance if it's working fine? Or did I fix some issue locally I've forgotten about?

**Comment by moumoutte** [comment]
> Have you tested an install of this package from Git against Django 2.2?
> 
> I have time to post a pypi release sometime in the next few days.

I've just run the tests set with tox and django22 (nothing more than travis I guess) and it's seems to be okay

```shell
py37-django22-sqlite installed: attrs==19.3.0,Django==2.2.9,django-bitfield==1.9.6,importlib-metadata==1.3.0,more-itertools==8.0.2,packaging==20.0,pluggy==0.13.1,psycopg2==2.8.4,py==1.8.1,pyparsing==2.4.6,pytest==5.3.2,pytest-django==3.7.0,pytz==2019.3,six==1.13.0,sqlparse==0.3.0,wcwidth==0.1.8,zipp==0.6.0

```

Is it enough ?

**Comment by joehybird** [comment]
Hi @timabbott, as master already supports django 2.2, it could be great if you have some time to post a new release soon :smile:

**Comment by timabbott** [comment]
Released: https://pypi.org/project/django-bitfield/2.0.0/.

Sorry for the delay.  Really I should arrange things so Mateusz can manage releases.

**Comment by joehybird** [comment]
Great job ! Thank you :smile:

**Comment by moumoutte** [comment]
Many thxs!
